### PR TITLE
fix: Check if user access token is valid before refresh

### PR DESCRIPTION
**Pull request by clundin25**
- fix: Check if user access token credential is valid before refreshing.

### CODE REVIEW

**Review by arithmetic1728 — APPROVED** [review]

**Review by arithmetic1728 — COMMENTED** [review]
this does not work, because this type of credential just gets token by running gcloud auth print-access-token, it doesn't even set the token property

**Comment by clundin25** [comment]
> this does not work, because this type of credential just gets token by running gcloud auth print-access-token, it doesn't even set the token property

Ah I see. So it should always refresh, as there is no way to track the expiry? We could consider querying the token info endpoint when the token is assigned, but I am not sure if that will save much performance

**Comment by clundin25** [comment]
Or add a gcloud API to query the token expiry

**Comment by arithmetic1728** [comment]
I think we might want to deprecate this credential type, and ask users to use user credentials instead. I added this credential type for mTLS usage because at that time user credential won't work. It's a google-auth specific credential.

**Comment by clundin25** [comment]
Makes sense @arithmetic1728, I think we should go ahead and deprecate then!

**Pull request closed without merging**
