### PR TITLE
feat: Make init.py to can load google.auth and google.outh2 with import google

### PR DESCRIPTION
**Pull request by CureSaba**
For fix this issue https://github.com/googleapis/google-auth-library-python/issues/1426
You can load google.auth and google.outh2 with import google

### CODE REVIEW

**Review by parthea — CHANGES_REQUESTED** [review]
If this change is accepted I believe we could run into issues like https://github.com/googleapis/google-cloud-python/issues/11399 where there is a conflict with other packages that use the `google` namespace.

**Comment by clundin25** [comment]
I don't see any benefits to introducing this change.

**Comment by CureSaba** [comment]
> If this change is accepted I believe we could run into issues like [googleapis/google-cloud-python#11399](https://github.com/googleapis/google-cloud-python/issues/11399) where there is a conflict with other packages that use the `google` namespace.

**Comment by CureSaba** [comment]
This pull request has been stopped to avoid conflicts with other libraries that use google mamespace.

**Pull request closed without merging**
