### PR TITLE
fix: retry token request on retryable status code

### PR DESCRIPTION
**Pull request by tommilligan**
See googleapis/google-cloud-python#15178

Implements the proposed change from the issue description.

cc @clundin25 as you already mentioned this seemed reasonable [here](https://github.com/googleapis/google-cloud-python/issues/15178#issuecomment-2252938836). I plugged this into the exponential retries as you mentioned.

### CODE REVIEW

**Review by clundin25 — APPROVED** [review]
Thank you for your contribution!

**Comment by tommilligan** [comment]
@clundin25 I pushed the branch again, CI looked to fail with something flaky and unrelated. Could you add the `kokoro:run` label again?

**Review by vchiapaikeo — APPROVED** [review]
Thank you for doing this!! We could really use this over at Etsy!

**Comment by clundin25** [comment]
@tommilligan Can you add a unit test for this change? It is failing the test coverage check.

`nox -s cover` is the coverage check command.

**Comment by tommilligan** [comment]
> @tommilligan Can you add a unit test for this change? It is failing the test coverage check.
> 
> `nox -s cover` is the coverage check command.

Thanks - updated with unit tests to cover success and failure paths, and rebased on `main`.

**Pull request merged**
