### PR TITLE
fix: aws path normalization in windows

### PR DESCRIPTION
**Pull request by bojeil-google**
Path normalization for the canonical_uri was broken in windows.
This is because we were using `os.path.normpath`.
This normalizes "/" paths to "\\" in Windows OS.

Confirmed the fix is working in Windows.

### CODE REVIEW

**Review by tseaver — APPROVED** [review]
Was there an issue opened for the broken window? :)

**Comment by bojeil-google** [comment]
> Was there an issue opened for the broken window? :)

It was open internally. It went through customer support. I can provide more details or open an issue if needed. Let me know your preference.

**Review by arithmetic1728 — APPROVED** [review]

**Comment by tseaver** [comment]
@bojeil-google The PR can merge without it, but having a link to the issue in the changelog might help folks figure out whether they had the problem fixed in whatever release.

**Comment by bojeil-google** [comment]
Fixes https://github.com/googleapis/google-auth-library-python/issues/844

**Comment by bojeil-google** [comment]
> @bojeil-google The PR can merge without it, but having a link to the issue in the changelog might help folks figure out whether they had the problem fixed in whatever release.

I agree. Done.

**Pull request merged**
