### PR TITLE
Fix: Less restrictive content-type header check for google authentication (ignores charset)

### PR DESCRIPTION
**Pull request by DanieleQuasimodo**
Less restrictive content-type header check for google authentication (now only the media-type is compared, ignoring charset, boundary, etc).
Should fix issue #1089.

Implemented as suggested in PEP-594 (due to deprecation of cgi.parse_header. See [https://peps.python.org/pep-0594/#cgi](https://peps.python.org/pep-0594/#cgi)).

### CODE REVIEW

**Comment by arithmetic1728** [comment]
@DanieleQuasimodo thank you for your PR. Could you add some unit tests to cover your change (for example, https://github.com/googleapis/google-auth-library-python/blob/main/tests/test__helpers.py and https://github.com/googleapis/google-auth-library-python/blob/main/tests/compute_engine/test__metadata.py).

**Comment by DanieleQuasimodo** [comment]
[These](https://github.com/googleapis/google-auth-library-python/pull/1382/commits/bda4f39ccb8efeffc0eaecfa227bad08a8e9162f) should do.
The _metadata test is probably a bit redundant (_metadata inner workings haven't really changed, except for invoking the new function which is already tested in the _helpers tests), but I still added it, just in case.

The forced push to my fork was just because I'm dumb, committed with the wrong account and had to ammend the author (so Google CLA is happy) 😅

**Comment by arithmetic1728** [comment]
@DanieleQuasimodo The PR looks great, thanks! Could you run `python -m nox -s lint` to format the files (this caused kokoro build failure)? After that I will go ahead to merge the PR.

**Comment by DanieleQuasimodo** [comment]
@arithmetic1728 I think now it should be ok.
I ran both blacken and lint

**Review by arithmetic1728 — APPROVED** [review]

**Pull request merged**
