### PR TITLE
fix: clean up HTTP session and pool during tear down phase

### LINKED ISSUE #271: ResourceWarning: unclosed SSLSocket
#### Environment details

  - OS type and version: Ubuntu 20.04 LTS
  - Python version: Python 3.8.10
  - pip version: pip 22.0.4
  - `google-cloud-secret-manager` version: 2.9.2

#### Steps to reproduce

  1. Create a file called `secret.py` with the following contents:
 ```
from google.cloud.secretmanager import SecretManagerServiceClient

with SecretManagerServiceClient() as client:
    response = client.access_secret_version(name='projects/project/secrets/secret/versions/latest')
```

  2. Execute `python -Wall secret.py`

#### Stack trace
```
.../lib/python3.8/site-packages/grpc/_channel.py:1548: ResourceWarning: unclosed <ssl.SSLSocket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('2a02:1210:22bd:8300:2b23:d126:3a74:f57b', 46782, 0, 0), raddr=('2a00:1450:400a:801::200a', 443, 0, 0)>
  self._channel.close(cygrpc.StatusCode.cancelled, 'Channel closed!')
ResourceWarning: Enable tracemalloc to get the object allocation traceback

```

### LINKED ISSUE #29227: ResourceWarning: unclosed SSLSocket
### What version of gRPC and what language are you using?
grpcio==1.44.0.
Python

### What operating system (Linux, Windows,...) and version?
Linux (Google)

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.9.9
```
gcc --version
gcc (Debian 11.2.0-16) 11.2.0
```

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
I ran the code example from [this issue](https://github.com/googleapis/python-secret-manager/issues/271).

### What did you expect to see?
I didn't expect to see warnings.

### What did you see instead?
I saw a similar warning as reported [this issue](https://github.com/googleapis/python-secret-manager/issues/271).
```
.../lib/python3.8/site-packages/grpc/_channel.py:1548: ResourceWarning: unclosed <ssl.SSLSocket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('2a02:1210:22bd:8300:2b23:d126:3a74:f57b', 46782, 0, 0), raddr=('2a00:1450:400a:801::200a', 443, 0, 0)>
  self._channel.close(cygrpc.StatusCode.cancelled, 'Channel closed!')
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
I'm able to reproduce the issue every time. I also tried debugging and wrapping the code in `contextlib.closing` but the warning persisted.
```
with contextlib.closing(secretmanager.SecretManagerServiceClient()) as client:
        response = client.create_secret(
            request={
                "parent": parent,
                "secret_id": "test2",
                "secret": {"replication": {"automatic": {}}},
            }
        )
 ```

### PR DESCRIPTION
**Pull request by lidizheng**
With help from @parthea , we are able to pin point the "creator" of the SSLSocket causing https://github.com/grpc/grpc/issues/29227.

This PR cleans the HTTP resources in the `__del__` methods.

Fixes: https://github.com/grpc/grpc/issues/29227
Fixes: https://github.com/googleapis/python-secret-manager/issues/271

### CODE REVIEW

**Comment by arithmetic1728** [comment]
Is it possible to add a simple test?

**Comment by lidizheng** [comment]
@arithmetic1728 It might be a non-trivial task. In the original reproduction, we rely on the warning message printed to console to know if the socket is leaked. If there isn't a memory-leak-detection job, it would be tricky to create an ad-hoc one.

Alternatively... we can add a test to explicitly invoke `Request.__del__` to see if session is closed. Do you think this will be useful?

**Comment by arithmetic1728** [comment]
@lidizheng yes that works. We just need some simple mock tests to cover the newly added lines.

**Comment by arithmetic1728** [comment]
`tests/transport/test_urllib3.py::TestRequestResponse::test_clear_pool_on_def` failed. 

I will fix the lint, and system test issue in a separate PR, they are not related to your change.

**Review by arithmetic1728 — APPROVED** [review]

**Pull request merged**
