### PR TITLE
chore(test): replace AWS creds with fictitious samples

### LINKED ISSUE #1324: Avoid committing hard coded secrets
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-auth-library-python/issues

looked and didn't see an open or closed issue related to this finding. 

If you are still having issues, please be sure to include as much information as possible:

#### Environment details
environment is probably not relevant to this static code finding, but just in case: 
  - OS: Linux 5.4.241-160.348.amzn2int.x86_64 
  - Python version:  3.7.16
  - pip version: 23.1.2 
  - `google-auth` version: 2.19.1

#### Steps to reproduce

1. notice that there are hard coded secrets in a test suite, specifically AWS account access key id, secret access key, and session token. why are hard coded secrets bad? https://maturitymodel.security.aws.dev/en/2.-foundational/dont-store-secrets-in-code/
2. if this was production code we'd recommend using AWS Secrets Manager, here's a helpful guide: https://docs.aws.amazon.com/secretsmanager/latest/userguide/hardcoded.html. 
3. since they are test only: replace with fictitious/mock values, AWS APIs suggest some examples such as:  https://docs.aws.amazon.com/STS/latest/APIReference/API_GetAccessKeyInfo.html and https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html in this case. 
4. profit, or non-profit as appropriate 

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

Welcome! Posting this issue for tracking, already have a pull request ready to resolve this finding. Thank you!

### PR DESCRIPTION
**Pull request by johnkrah-aws**
We recommend (1) removing these secrets from code and (2) rotating the account access secret key to prevent unauthorized use by anyone who has seen the credentials written here. Consider using AWS Secrets Manager to store and access credentials, here’s a more detailed explanation https://maturitymodel.security.aws.dev/en/2.-foundational/dont-store-secrets-in-code/ why this is a best practice and a helpful guide
https://docs.aws.amazon.com/secretsmanager/latest/userguide/hardcoded.html how to implement.

Alternately in case these are purely test strings we recommend using a recognizably mocked value to assure that there is no accidental disclosure of credentials suggested by
https://docs.aws.amazon.com/STS/latest/APIReference/API_GetAccessKeyInfo.html and
https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html.

Fixes #1324 

Contribution guide checklist 
[x] have an organization and individual contributor license agreement on file 
[x] forked repo and dev/test on my fork, don't believe a doc is needed for this test config change 
[x] added details in the commit message and duplicated above ^^ 
[x] submitting this pull request 
[x] have not modified nor made a new feature 
[x] full nox test suite verified working on python 3.7 and 3.8 in linux, since the change is string literal assignment with no declarations I don't expect any difference across os/py versions 
[x] test coverage remains 100%, no added lines of code 

let me know any changes I can make to improve the quality of this PR, thanks!

### CODE REVIEW

**Comment by johnkrah-aws** [comment]
I see the conventional commits validation failed and will adjust this afternoon.

**Comment by clundin25** [comment]
@johnkrah-aws LGTM after commit check passes

**Comment by lsirac** [comment]
IIRC these were copied from the AWS test suite. There is no reason to change them @clundin25

**Comment by clundin25** [comment]
@lsirac which test suite are you referencing? 

Either way, this change seems to mostly be cosmetic.

**Comment by johnkrah-aws** [comment]
updated commit message to follow conventional commits rule, its automatic check has passed now. 

correct this PR does not change any feature/behavior of the library only addresses hard coded secrets finding.

**Comment by clundin25** [comment]
@johnkrah-aws will the proposed change prevent this codebase from appearing as a false-signal in scanners searching for real committed AWS credentials?

**Comment by johnkrah-aws** [comment]
yes @clundin25 that's correct. scanners that look for AWS account secrets do find the hard coded creds in this test file, and do/should not find the example creds. we also fork this library internally and our AWS Code Guru static analysis flagged this instance for us. and I have confirmed on our internal fork that the proposed fix resolved the AWS Code Guru finding. 

I can't guarantee for all code scanners in the world, but if they are following the partner guidance for real secrets and sample/mock/fictitious secrets then should be clear sailing.

**Comment by lsirac** [comment]
The other auth libs use these creds too btw. I also couldn't find it in the aws test suite @clundin25

**Review by lsirac — APPROVED** [review]

**Review by clundin25 — APPROVED** [review]

**Pull request merged**
