### PR TITLE
chore: Add deprecation notice for 3.7.

### PR DESCRIPTION
**Pull request by clundin25**

### CODE REVIEW

**Comment by arithmetic1728** [comment]
it seems some unit test is needed to cover the new changes

**Comment by clundin25** [comment]
> it seems some unit test is needed to cover the new changes

Good catch, I'll add those

**Comment by arithmetic1728** [comment]
gcloud will drop 3.7 on sep 26, let's hold on until then

**Comment by clundin25** [comment]
@arithmetic1728 sounds good 👍

**Comment by clundin25** [comment]
@arithmetic1728 I am okay with waiting but I think this change is still safe, it is just a deprecation notice that would impact some users

**Review by arithmetic1728 — APPROVED** [review]

**Pull request merged**
